services:
  app:
    build: .
    container_name: team1-front
    ports:
      - "10400:8080"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"