spring:
  application:
    name: team1-front
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT:10404}

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry
  endpoint:
    health:
      show-details: never

gateway:
  url: http://localhost:10400

juso:
  confirm-key: ${JUSO_CONFIRM_KEY:}

security:
  jwt:
    issuer: ${JWT_ISSUER:account-api}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:1m}
    allowed-algorithms:
      - rs256
    jwk-set-uri: ${JWK_SET_URI:http://localhost:10413/.well-known/jwks.json}
  refresh-token:
    ttl: ${REFRESH_TOKEN_TTL:14d}
