spring:
  application:
    name: team1-front
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: ${SERVER_PORT:10404}

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry
  endpoint:
    health:
      show-details: never

gateway:
  url: http://localhost:10400
