eureka:
  client:
    enabled: false
  
management:
  tracing:
    export:
      enabled: false

cookie:
  secure: false

security:
  jwt:
    issuer: ${JWT_ISSUER:account-api}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:30m}
    allowed-algorithms:
      - rs256
    jwk-set-uri: ${JWK_SET_URI:http://localhost:10413/.well-known/jwks.json}

app:
  api-base-url: http://localhost:10400
