eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    # 더 이상 프론트 레지스트리가 필요하지 않음
    register-with-eureka: false
    # 하지만 다른 서비스 목록은 필요
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:10402/eureka/}
    refresh:
      enable: false

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry, prometheus
  tracing:
    sampling:
      probability: 1  # 트래픽 봐서 낮추기
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}

gateway:
  url: lb://team1-gateway

cookie:
  secure: true

security:
  jwt:
    issuer: ${JWT_ISSUER:account-api}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:30m}
    allowed-algorithms:
      - rs256
    jwk-set-uri: ${localhost:10413/.well-known/jwks.json}]
    audiences:
      - front

juso:
  confirm-key: ${JUSO_CONFIRM_KEY}